openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
  description: A simple API to fetch weather information for a specific city
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /weather/{city}:
    get:
      summary: Get weather data for a city
      description: Fetches weather data for the specified city.
      parameters:
        - in: path
          name: city
          required: true
          schema:
            type: string
          description: City for which to fetch the weather
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    type: number
                    description: Current temperature.
                    example: 20
                  humidity:
                    type: number
                    description: Current humidity.
                  wind:
                    type: number
                    description: Current wind.
                  rain:
                    type: number
                    description: Current rain.
        '404':
          description: City not found
        '500':
          description: Server error 

/forecast:
    get:
      summary: Get a three-day weather forecast for London
      description: Returns the temperature forecast for the next three days.
      responses:
        "200":
          description: Successful response with three-day forecast
          content:
            application/json:
              schema:
                type: object
                properties:
                  dayOne:
                    type: integer
                    description: Temperature on the first day.
                    example: 14
                  dayTwo:
                    type: integer
                    description: Temperature on the second day.
                    example: 23
                  dayThree:
                    type: integer
                    description: Temperature on the third day.
                    example: 17
        "500":
          description: Internal server error  

